### PR TITLE
Custom filter callback

### PR DESCRIPTION
**Pull request by phlptp**
### Summary

If merged this pull request will add a custom callback for filters to the C shared library

### Proposed changes

- add callback function
- add a messageCopy function
- add some tests for new functions

### CODE REVIEW

**Comment by phlptp** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/helics/shared_library/test-message-federate.cpp  2
- tests/helics/shared_library/FilterTests.cpp  19
         

Clones removed
==============
+ src/helics/shared_api_library/MessageFiltersExport.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GMLC-TDC/HELICS/pullRequest?prid=5183098&bid=17007644)

**Comment by phlptp** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tests/helics/shared_library/FilterTests.cpp  19
- tests/helics/shared_library/test-message-federate.cpp  2
         

Clones removed
==============
+ src/helics/shared_api_library/MessageFiltersExport.cpp  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GMLC-TDC/HELICS/pullRequest?prid=5183098&bid=17007644)

**Comment by phlptp** [comment]
@kdheepak Can you take a look at this as well,  I want your thoughts on the structure of the callback for filters.

**Comment by kdheepak** [comment]
- This interface is similar to the logging callback, which is good for consistency
- I think the documentation doesn't make it clear on when callbacks are triggered. Perhaps this is a separate issue, but we need a lifecycle diagram or flowchart or bar chart of schedules of all the events in the software i.e. _when_ everything happens in HELICS. 

This looks good to me from a C/Python/Julia/MATLAB interface perspective.

**Comment by phlptp** [comment]
> * I think the documentation doesn't make it clear on when callbacks are triggered. Perhaps this is a separate issue, but we need a lifecycle diagram or flowchart or bar chart of schedules of all the events in the software i.e. _when_ everything happens in HELICS.

That is probably a good idea, but would be part of a bigger documentation effort

**Pull request merged**
