### PR TITLE
Add macOS installers and Linux shared library to release build workflow

### PR DESCRIPTION
**Pull request by nightlark**
### Summary

If merged this pull request will add builds for a macOS and Linux shared library, and a macOS archive that includes some extras like the compiled apps to the releases workflow.

Latest test run at https://github.com/nightlark/HELICS/releases/tag/vMac.7 (MSVC archive builds failed due to swig archive not downloading, probably sourceforge issues -- rerun is at https://github.com/nightlark/HELICS/releases/tag/vMac.8)

### Proposed changes
- Add a macOS and Linux shared libraries (+ headers and swig *.i files) to the release build workflow
- Add a macOS archive that includes pre-compiled apps and some interfaces to the release build workflow

### CODE REVIEW

**Comment by phlptp** [comment]
@kdheepak can you take a look at this as well

**Comment by phlptp** [comment]
@nightlark can you add a note in the changelog referencing this(if I didn't to it already), you can do it in this PR or #894

**Comment by phlptp** [comment]
This will close #648

**Comment by nightlark** [comment]
The changelog in the doc update branch has been updated to reference this change.

The binaries were built on macOS 10.15 and Ubuntu 18.04, so for now I'm putting those as the supported versions. The Linux one should work on other distributions and older versions. I'm not sure about on macOS, there was an Xcode setting file that mentioned 10.11 as a minimum. For the upcoming release I don't want to make any guarantees about them working on older versions in case something needs to change like building the Linux one in a docker container with an old version of glibc.

**Comment by nightlark** [comment]
Some notes on building a macOS package using CPack and why it's currently using TGZ:
- Bundle generator creates a .app file which doesn't really work since we don't have a main binary with a gui
- DragNDrop dmg generator had the bin/lib/etc folders at the top level, which looked messy
- PackageMaker is deprecated/no longer in macOS
- productbuild generator creates a .pkg installer which is nice, except it doesn't allow picking an install folder other than a drive (and it asked for a password to run)

The Qt IFW generator might be one to explore for future releases -- since it's cross-platform, it could be a way to get a gui-based installer that's consistent across Windows/macOS/Linux.

**Pull request merged**
