### PR TITLE
Add SWIG interface file update GitHub Action

### PR DESCRIPTION
**Pull request by nightlark**
### Summary
If merged this pull request will add a GitHub Actions workflow to create pull requests to develop for updating the generated SWIG interface files.

Example PR created: https://github.com/nightlark/HELICS/pull/6

### Proposed changes
- Add a swig interface file update PR GitHub Actions workflow
- Change the title of the release build workflow to better describe it than "Release all submodules archive"

### CODE REVIEW

**Comment by phlptp** [comment]
So from what I can tell,  this generates the new interface files using the docker container for that. 

Copies them over into a different docker that does the comparison and then generates  a PR?

Is that pretty much the gist of it?

**Comment by nightlark** [comment]
Something like that, but no copying is used -- it mounts a workspace as a shared volume for the containers.

**Comment by nightlark** [comment]
I tried to make the part that pushes a branch and creates a PR with changed files an action that can be reused in other workflows.

**Comment by phlptp** [comment]
Do we want to wait to merge this until after @kdheepak commit to develop or before?  If before I think you can merge

**Comment by nightlark** [comment]
I'll merge now (expecting a PR that updates swig version numbers), then when Dheepak opens a PR with the fix to develop we can make sure it works with the entire cycle of a PR (e.g. runs after it gets merged).

**Pull request merged**
