### PR TITLE
Add filter federate example documentation

### PR DESCRIPTION
**Pull request by trevorhardy**
### Summary

Adds documentation for filter federate example as a part of the User Guide for v3.

Also adds a template for the native filter write-up.

### CODE REVIEW

**Comment by phlptp** [comment]
looks like a few formatting issues need to be resolved, then I think we could merge this assuming the actual content is good to go.

**Comment by nightlark** [comment]
Okay, so the workflow for compressing images has a condition for pushing optimized images inverted. https://github.com/GMLC-TDC/HELICS/pull/1889 fixes it, I think if this PR is rebased after that gets merged then only the compressed images will make it into the repository history.

**Comment by nightlark** [comment]
Looks like there are quite a few images that were never optimized. Future PRs with images added should just result in the new images getting compressed.

**Comment by phlptp** [comment]
@trevorhardy  unless you tell me otherwise I am going to merge this, and we can polish it up if needed between the beta and final

**Comment by trevorhardy** [comment]
I won't have time to get to this for a few more days so go ahead.

**Review by phlptp — APPROVED** [review]

**Pull request merged**
