### PR TITLE
Register `helicsCloseLibrary` as an `atexit` for python code generated from SWIG

### LINKED ISSUE #858: Add `atexit` callback to helicsCloseLibrary in language bindings
I ran the same code in Julia and Python. The code creates a value federate without starting a broker. HELICS errors as expected with a registration failure error.

In Julia, when the error occurs, the remaining lines in the file are not executed, and the process exits. The error code is `1` for the process.

In Python, when the error occurs, the remaining lines in the file are not executed as expected, but when the process tries to exit it just hangs. The user must then run `Ctrl+C` to terminate the process. The error code is `SIGINT(2)` for the `Ctrl+C` and the error code of the process is lost.

Screen Shot 2019-10-25 at 2 02 02 PM

See screenshot for example of this.

In Julia, I added [one line](https://github.com/GMLC-TDC/HELICS.jl/commit/d590fa548710361e00d6f614a8ed63aecb5b485f) that adds `helicsCloseLibrary` as a callback when the process exits, using `atexit` and that provides a nicer user experience during these errors.

### PR DESCRIPTION
**Pull request by kdheepak**
### Summary

If merged this pull request will register a `atexit` call to `helicsCloseLibrary`.

Fixes #858

### CODE REVIEW

**Comment by phlptp** [comment]
@kdheepak,  you verified this works?  
is atexit something that is universally available or would people have to install it?

**Comment by kdheepak** [comment]
`atexit` is standard library module built into Python3/Python2.

https://docs.python.org/3/library/atexit.html

https://docs.python.org/2/library/atexit.html

And I verified that it works as expected.

```
$ python pireceiver.py
PI RECEIVER: Helics version = 2.2.1 (09-27-19)
PI RECEIVER: Creating Federate Info
PI RECEIVER: Setting Federate Info Name
PI RECEIVER: Setting Federate Info Core Type
PI RECEIVER: Setting Federate Info Init String
PI RECEIVER: Setting Federate Info Time Delta
PI RECEIVER: Creating Value Federate
commWarning||TestB Federate:zmq broker connection timed out, trying again (2)
commWarning||TestB Federate:sending message to tcp://127.0.0.1:23405
commERROR||TestB Federate:zmq broker connection timed out after trying 5 times (2)
commERROR||TestB Federate:receiver connection failure
Traceback (most recent call last):
  File "pireceiver.py", line 38, in <module>
    vfed = h.helicsCreateValueFederate("TestB Federate", fedinfo)
  File "/Users/USER/local/helics-develop/python/helics.py", line 311, in helicsCreateValueFederate
    return _helics.helicsCreateValueFederate(fedName, fi)
_helics.HelicsException
```

This returns back to the shell after the timing out and returns error code 1.

**Comment by phlptp** [comment]
Anyone care to explain this [error](https://travis-ci.com/GMLC-TDC/HELICS/jobs/249932154)?

**Comment by kdheepak** [comment]
```
[ 43%] Building CXX object src/helics/core/CMakeFiles/helics_core.dir/zmq/ZmqRequestSets.cpp.o

[ 44%] Building CXX object src/helics/core/CMakeFiles/helics_core.dir/zmq/ZmqCommsCommon.cpp.o

[ 44%] Built target helics_core

Scanning dependencies of target helics-shared

Scanning dependencies of target helics-static

[ 45%] Linking CXX static library libhelics-static.a

[ 45%] Building CXX object src/helics/CMakeFiles/helics-shared.dir/__/empty.cpp.o

[ 45%] Linking CXX shared library libhelics-shared.so

core/CMakeFiles/helics_core.dir/TimeCoordinator.cpp.o: file not recognized: File truncated

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make[2]: *** [src/helics/libhelics-shared.so.2.2.2] Error 1

make[1]: *** [src/helics/CMakeFiles/helics-shared.dir/all] Error 2

make[1]: *** Waiting for unfinished jobs....

[ 45%] Built target helics-static

make: *** [all] Error 2
```

We should restart the build and see if it happens again.

**Comment by phlptp** [comment]
I have restarted it 3 times with the same issue every time and it did the same thing after merging master back into it, so I have no idea right now.  I might try to delete the cache and try again see if something weird happened in the cache.

**Comment by phlptp** [comment]
must have been something in the cache,  since it is passing now.

**Comment by phlptp** [comment]
Is this ready to merge @kdheepak?

**Comment by kdheepak** [comment]
Yes it's ready to merge!

**Pull request merged**
