### PR TITLE
Fix cmake HELICS_ENABLE_LOGGING bug

### LINKED ISSUE #2229: First build has logging disabled
This block generates the `helics-config.h` file.

https://github.com/GMLC-TDC/HELICS/blob/39470e8a75f7fa931357f5016391432bfc99f1f7/CMakeLists.txt#L542-L548

However, `HELICS_ENABLE_LOGGING` isn't set to `ON` until later in the file.

https://github.com/GMLC-TDC/HELICS/blob/39470e8a75f7fa931357f5016391432bfc99f1f7/CMakeLists.txt#L651-L658

This causes the first run of cmake to have logging disabled. Subsequent runs of cmake appear to use the `HELICS_ENABLE_LOGGING` value from the cache which is set to `ON`. 

image

### PR DESCRIPTION
**Pull request by kdheepak**
Fixes #2229

### CODE REVIEW

**Comment by phlptp** [comment]
I am going to merge this,  looks like there is a tsan error that shows up from fixing this that I need to resolve as well so I will work on that today.

**Review by phlptp — APPROVED** [review]

**Review by phlptp — APPROVED** [review]

**Comment by phlptp** [comment]
@kdheepak  do we need this one any more I merged into the commit when I fixed the tsan issue.

**Comment by phlptp** [comment]
going to close this as the changes were merged with #2231

**Comment by kdheepak** [comment]
Thanks!

**Pull request closed without merging**
