### PR TITLE
Improved iteration example documentation.

### PR DESCRIPTION
**Pull request by eranschweitzer**
### Summary

If merged this pull request will add some more background to the documentation of the iteration example as well as show plots comparing results when iteration is used versus when it is not.

### Proposed changes

Docs changes only to the iteration example.

### CODE REVIEW

**Review by trevorhardy — APPROVED** [review]

**Comment by phlptp** [comment]
@eranschweitzer  can you resolve the conflict in this and double check if it is ready for a merge

**Comment by eranschweitzer** [comment]
@trevorhardy what are your referring to with examples working better? The iteration examples are working just fine as far as I know.

@phlptp I'll take a look. This should be docs changes only, so I don't really know why there should be conflicts

**Comment by phlptp** [comment]
@eranschweitzer  Looks like it is just the index file in the documentation that is conflicting with doc additions from the other PR's

**Comment by eranschweitzer** [comment]
@phlptp that should hopefully resolve it. I don't know why it happened but the base was changed from docs3.3 to develop which led to the conflicts.

**Pull request merged**
