### PR TITLE
Build Windows installers and a SHA-256 hash file for releases

### PR DESCRIPTION
**Pull request by nightlark**
### Summary

If merged this pull request will add several Windows installer builds to releases using GitHub actions, and generate a SHA-256.txt file with hashes for the Windows installers and all submodules source code archive to address issue #810. Also related to #648, automatic installer generation.

VMs for Windows builds can take some time to start, and compiling takes ~10 minutes. Overall time after publishing a release for the files to appear is probably 15-30 minutes. Test releases: https://github.com/nightlark/HELICS/releases/tag/v2.2.0.9 and https://github.com/nightlark/HELICS/releases/tag/v2.2.0.11

### Proposed changes
- Build HELICS Windows installers (32-bit and 64-bit variants) using Visual Studio 2017 and 2019, with Python 3.7 interface
- Generate a SHA-256.txt file for HELICS releases with hashes for the Windows installers and the source code archive containing all submodules

### CODE REVIEW

**Comment by nightlark** [comment]
Currently assets are uploaded to the release as soon as they are ready, and generating the SHA-256 file happens at the end with the artifacts from the previous steps. This could be changed to upload all of the assets to the release at the end.

There aren't VM images with VS2015, so it's just 2017 and 2019 installers built with the C and C++ shared libraries, static libraries, apps, and the Python 3.7 interface. I'm not sure how to deal with multiple Python versions without a large increase in the number of assets that need generating -- separate installers for different Python versions in 32/64-bit variants would be an approach.

If someone needs a debug build of the libraries, I think that might be a point at which they should build HELICS from source, or eventually with a package manager that allows switching compiler options.

**Comment by phlptp** [comment]
what is the default python installed with VS2017 Release?  with VS2019?  and is the python included in these images the one with Visual studio or a separate installation.

What I had done before is VS2017 Release, VS2017 Debug,  VS2017 Release (static std lib) with exe and zip file.

I think we also need to answer questions of how we want to publish Matlab interface and Java interface potentially in isolation from the other libraries like the installers here.  

So as far as I can tell the PR looks good but a little discussion on what exactly we want as far as installers go might be warranted

**Comment by nightlark** [comment]
I don't think there is any special Visual Studio version of Python. All of the versions are installed in C:/hostedtoolcache/windows/, the default one added to the PATH is 3.6; the other versions that can be added to PATH instead are 2.7, 3.4, 3.5, 3.6, and 3.7.

**Comment by phlptp** [comment]
then it is probably worth it to build against 3.6 so it is most likely compatible with 3.6 and 3.7+

**Comment by nightlark** [comment]
Set of files for releases based on discussion today:
- gzip file with all code
- VS2017 and VS2019 64-bit zip files with debug + release variants
- Generic HELICS installer (exe+zip) (64-bit) for executables and C shared library (static std lib) with Python 3.6 and Java 1.8 interfaces
- Zip with C shared library with C/C++98 headers (and swig interface files)
- Matlab interface

**Comment by phlptp** [comment]
@kdheepak  What are you thoughts on the above list?

**Comment by phlptp** [comment]
@nightlark are you planning to update this more, or do we want to merge this and work on the rest of the list in the 2.3 release?

**Comment by kdheepak** [comment]
I would like a tar with C shared library with C/C++98 headers and no swig interfaces.

**Comment by nightlark** [comment]
@kdheepak would the one with the swig interface files work? It just has the `helics.i` and `output.i` files in the `share/helics/swig` subfolder, none of the language specific interfaces or files.

**Comment by phlptp** [comment]
@kdheepak  what platform?

**Comment by kdheepak** [comment]
> would the one with the swig interface files work? It just has the helics.i and output.i files in the share/helics/swig subfolder, none of the language specific interfaces or files.

Okay, this works! I thought it had the compiled files. 

I'd like this for all platforms, Windows, Mac and Linux; with x86 and x64.

**Comment by nightlark** [comment]
If we aren't releasing 2.2.1 today, then I'll change the set of uploaded installers from the current msvc ones to these:
- VS2017 and VS2019 64-bit zip files with debug + release variants
- Generic HELICS installer (exe+zip) (64-bit) for executables and C shared library (static std lib) with Python 3.6 and Java 1.8 interfaces
- Zip(/tar) with C shared library with C/C++98 headers (and swig interface files); Windows x86/x64

Archives with the shared library for other platforms will likely be for the release after.

**Comment by phlptp** [comment]
I want to get the broker timeout in yet, and that will hopefully get finished over the weekend, so the most realistic target would be next Tuesday for a release.

**Pull request merged**
