### PR TITLE
Helics3userguide rebased

### PR DESCRIPTION
**Pull request by trevorhardy**
### Summary

Merge the HELICS 3 User Guide into main helics3 branch.

If merged this pull request will provide updated documentation for HELICS 3.

### CODE REVIEW

**Comment by phlptp** [comment]
@trevorhardy  any issues during the rebase process?

Can you take a look through the formatting PR onto this one, make sure nothing is amiss,  then you can merge that.

Should I do a squash on this or do you want to keep the individual commits separate?

**Comment by trevorhardy** [comment]
Rebase went pretty smoothly (with help from @eberleim to navigate the process); I confident I resolved the limited number of conflicts well.

I think we're OK squashing the commits; there's a lot of them and many of them are not significant.

I'll merge in the content from the formatting PR; nothing looks crazy there to me.

**Comment by trevorhardy** [comment]
OK, @phlptp; I've reviewed (and corrected) the auto-formatting changes and merged those into this PR.

**Comment by trevorhardy** [comment]
Looks like the formatting is still failing; let me look it over.

**Comment by trevorhardy** [comment]
Super minor; should be good now.

**Review by phlptp — APPROVED** [review]

**Pull request merged**
