### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by phlptp**
### Summary

If merged this pull request will merge remaining develop changes in to master, to prepare to move develop to switch to HELICS 3 ( soon to be `main`) branch.

### CODE REVIEW

**Review by nightlark — APPROVED** [review]

**Comment by nightlark** [comment]
It looks like using merge strategy `ours` or `theirs` (non-recursive versions) basically just makes the resulting set of files equivalent to the branch selected.
https://git-scm.com/docs/merge-strategies#Documentation/merge-strategies.txt-ours

**Comment by phlptp** [comment]
So I should merge helics3 to develop and use strategy "ours"?

**Comment by nightlark** [comment]
It would probably be:
```
git checkout helics3
git merge -s ours <develop/helics2/master>
git checkout <develop/helics2/master>
git merge helics3
```
That would discard all of the changes from helics2 first, then fast-forward merge the develop branch to be equivalent to helics3. The 2nd merge would probably be roughly equivalent to deleting develop and renaming the helics3 branch to develop.

**Comment by phlptp** [comment]
So basically 
make a branch for helics2 based on current master

do some merge magic to make helics3 mergeable to master.

merge to master

delete develop
and helics3 branches

rename master to main

create a new develop branch based on new main

**Comment by nightlark** [comment]
That sounds like it should work.

**Pull request merged**
