### PR TITLE
Add timeout test

### PR DESCRIPTION
**Pull request by kdheepak**
### Summary

If merged this pull request will add a new timeout test in Python for a value federate. It initializes a federate, enters execution and waits 60 seconds, and then checks if the broker is still connected.

This test can be run explicitly by using the following:

```
pytest -sv tests/python/test_value_federate.py -k test_value_federate_runFederateTimeoutTest
```

Related to #853

### CODE REVIEW

**Comment by nightlark** [comment]
Does pytest have a way to control which tests are run similar to GoogleTest filters or Boost.Test labels?

**Comment by kdheepak** [comment]
Yes, using command line arguments. The example I shared above runs just one test. If you use `pytest -sv tests/python/test_value_federate.py` instead, it runs just the tests in that file. Is that what you are asking?

**Comment by nightlark** [comment]
I was thinking for the opposite case, to run everything except the listed test.

**Comment by kdheepak** [comment]
There's a way to mark specific tests as ones that will be skipped or ones that will fail.

https://docs.pytest.org/en/latest/skipping.html

We have to do it in the code though. It's a one line addition to can mark this as one that should fail.

**Comment by nightlark** [comment]
I think it's one that should be marked as skipped, then in the cmake a new add_test can be added that runs this specific test with some label that can separate it from faster tests.

**Comment by phlptp** [comment]
I can easily see a number of this type of tests being needed in the future.  There should be a way to disable them easily.  Or have them be disabled by default an only run in some of the CI builds.

**Comment by kdheepak** [comment]
If this `HELICS_PYTHON_ADDITIONAL_TESTS` is set to any value except an empty string, this test will run. `export HELICS_PYTHON_ADDITIONAL_TESTS=""` is the default and will result this test not being run.

In the future we can add additional conditions, e.g. if `export HELICS_PYTHON_ADDITIONAL_TESTS="value,message"`, run the additional value and message federate tests but not the additional filter tests.

**Comment by kdheepak** [comment]
I'm getting this error when I try to build this branch from source:

```
[ 43%] Linking CXX static library libhelics-static.a
[ 43%] Built target helics-static
tests/helics/performance_tests/CMakeFiles/perf-tests.dir/build.make:115: *** target pattern contains no `%'.  Stop.
make[1]: *** [tests/helics/performance_tests/CMakeFiles/perf-tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
tests/helics/application_api/CMakeFiles/application-api-tests.dir/build.make:325: *** target pattern contains no `%'.  Stop.
make[1]: *** [tests/helics/application_api/CMakeFiles/application-api-tests.dir/all] Error 2
```

I used `cmake -DBUILD_PYTHON_INTERFACE=ON -DCMAKE_INSTALL_PREFIX="/Users/$USER/local/helics-develop/" ../`. 

I added `-DBUILD_HELICS_TESTS=OFF` to make the above error go away.

And I was able to run the test and verify that it is in fact now resolved on this branch!

```
pytest -sv tests/python/test_value_federate.py -k test_value_federate_runFederateTimeoutTest
============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.7.3, pytest-5.2.1, py-1.8.0, pluggy-0.13.0 -- /Users/USER/miniconda3/bin/python
cachedir: .pytest_cache
rootdir: /Users/USER/GitRepos/HELICS
collected 14 items / 13 deselected / 1 selected

tests/python/test_value_federate.py::test_value_federate_runFederateTimeoutTest PASSED

================================================================== 1 passed, 13 deselected in 60.32s (0:01:00) ===================================================================
```

The fix works!

**Comment by phlptp** [comment]
I think we resolved the error you were getting in 2.3,  might have had to do with finishing converting everything to google tests

**Comment by phlptp** [comment]
do we want to tag a bug fix release with this or just wait two weeks for 2.3?

**Comment by kdheepak** [comment]
I would like a bug fix release.

**Comment by phlptp** [comment]
I updated the release documents with the version number and date and the changelog and also fixed the readme with the correct links for travis-ci.

**Comment by phlptp** [comment]
@nightlark  can you review?

**Comment by phlptp** [comment]
@kdheepak do another review then once the required CI builds have completed you can go ahead and merge

**Comment by kdheepak** [comment]
Looks good to me!

**Pull request merged**
