### PR TITLE
Add uuid support in the webserver

### PR DESCRIPTION
**Pull request by phlptp**
### Summary

If merged this pull request will add uuid support for broker names and the field in some queries, and support for generating UUID broker names in the webserver.  

### Proposed changes

- uuid support in webserver
- appropriate respond fields from generating a broker
- uuid field in some queries if a uuid was used as the broker name

### CODE REVIEW

**Comment by phlptp** [comment]
@nightlark  why is the azure builds failing now?  I don't think we changed anything related to that.

**Comment by nightlark** [comment]
It's failing on the CMake task...
```
      - task: CMake@1
        inputs:
          cmakeArgs: -A $(vsArch) -DHELICS_ENABLE_SWIG=ON -DHELICS_BUILD_CXX_SHARED_LIB=ON -DHELICS_ENABLE_PACKAGE_BUILD=ON -DHELICS_BUILD_TESTS=ON -DHELICS_BUILD_EXAMPLES=ON ..
        displayName: 'Configure HELICS'
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
```

That task then creates the command to run, which for some reason it's now splitting binary to run instead of treating it as a long quoted path.
```
"C:\Program Files\CMake\bin\cmake.exe" -A Win32 -DHELICS_ENABLE_SWIG=ON 
-DHELICS_BUILD_CXX_SHARED_LIB=ON -DHELICS_ENABLE_PACKAGE_BUILD=ON -DHELICS_BUILD_TESTS=ON -DHELICS_BUILD_EXAMPLES=ON ..
'C:\Program' is not recognized as an internal or external command, operable program or batch file.
```

It seems to be affecting a few people, there's already an issue for it:
https://github.com/microsoft/azure-pipelines-tasks/issues/13044

**Comment by phlptp** [comment]
I am going to merge this and hope the azure build is resolved soon

**Comment by nightlark** [comment]
They have PR to fix it: https://github.com/microsoft/azure-pipelines-tasks/pull/13058

**Pull request merged**
