### PR TITLE
Test fails

### PR DESCRIPTION
**Pull request by phlptp**
### Summary

If merged this pull request will fix a few issues with the test cases
namely #1138 
#1132 

an attempt at fixing #1134 
and might be related to #967 though that one hasn't failed in a while.  

### Proposed changes

- rework how the queries are handled at the core level 
- add camelCase handlers for input file properties

### CODE REVIEW

**Comment by phlptp** [comment]
pretty sure there was a few cases with global variables that would fail before this PR as well in the case of intermediate brokers.  These cases were never tested but maybe should be at some point soon.

**Comment by nightlark** [comment]
Something that looks like it will trip up some languages that have built-in json/toml marshaling support is having underscore and non-underscore (or alternative) names for the same field. At some point (HELICS 3.0) we might want to pick a preferred variant for each field that we say to use if you want your config file to work with 3rd party tools/languages.

**Comment by phlptp** [comment]
@kdheepak  can you take a look and see what this does with #1134

**Comment by kdheepak** [comment]
I checked out this branch locally and built from source. I still get the same error posted in the issue you referenced.

**Comment by phlptp** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Clones removed
==============
+ src/helics/core/NetworkBrokerData.cpp  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GMLC-TDC/HELICS/pullRequest?prid=5197382&bid=17044903)

**Comment by phlptp** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ src/helics/core/NetworkBrokerData.cpp  -4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GMLC-TDC/HELICS/pullRequest?prid=5197382&bid=17044903)

**Comment by phlptp** [comment]
@kdheepak  can you update and try again?

**Comment by kdheepak** [comment]
Works!

**Comment by kdheepak** [comment]
```
$ ctest -R core-tests --output-on-failure

Test project /Users/USER/gitrepos/HELICS/build-osx
    Start 8: core-tests
1/1 Test #8: core-tests .......................   Passed   40.07 sec

100% tests passed, 0 tests failed out of 1

Label Time Summary:
Core        =  40.07 sec*proc (1 test)
Coverage    =  40.07 sec*proc (1 test)
Daily       =  40.07 sec*proc (1 test)

Total Test time (real) =  40.08 sec
```

**Pull request merged**
