### PR TITLE
Fix logging tsan

### PR DESCRIPTION
**Pull request by phlptp**
### Summary

If merged this pull request will fix the tsan warning generated from fixing #2230

### CODE REVIEW

**Review by kdheepak — APPROVED** [review]

**Comment by kdheepak** [comment]
I’m worried there may be other cmake related issues like this. Any ideas on how we might find them?

**Comment by phlptp** [comment]
I don't know,  we have a number of CI builds with different CMake options.   I have looked around on occasion for a CMake "fuzzer" but haven't found anything like that yet.  

I was looking at it a bit closer trying to figure out why the tests passed.  What was being checked is the logging system, via api generated messages, which wasn't affected.    What the CMake flag controlled was the internally generated log messages which were being shut off.  Could probably add a test to check for them but not sure it would add much value right now.

**Comment by nightlark** [comment]
What would you want a CMake "fuzzer" to do? Just run the configure step with a bunch of flag combinations (valid + invalid) and report which ones fail configuration (or produce a CMakeCache.txt file that doesn't match some expected output), or would a build + test run also need to be done?

**Comment by phlptp** [comment]
For a fuzzer  the first would be to start trying a variety of CMake options in combinations.  And just trying to build.  There are several issues we had in the past that would have been caught that way.  I suppose a more time consuming step would be to change the options and run the tests make sure the tests pass under the different conditions.

**Comment by nightlark** [comment]
I guess the easiest way to start out would be having the user provide a list of options that in isolation are valid, and then have it pick random combinations -- discovering options could get complicated for dependent options.

CMake provides a --trace option that shows every line executed, so a coverage tool that checks if any paths in the CMake files are skipped might be relatively easy to create.

**Pull request merged**
