### PR TITLE
Helics export target

### PR DESCRIPTION
**Pull request by phlptp**
### Summary

If merged this pull request will update cmake so the export command and the cmake output can be controlled and update the config file with a utilities target 

### Proposed changes

- update msys build instructions
- add EXPORT target control option to cmake
- add option for generating cmake config target output
- add HELICS::utilities target

### CODE REVIEW

**Comment by nightlark** [comment]
Other than the failing add_subdirectory test, the changes look okay.

**Comment by phlptp** [comment]
@nightlark  I am going to update the version number on this since I need the discrimination to use this in HELICS-FMI

**Comment by phlptp** [comment]
@nightlark  can you take a look at this again.  I have made a number of changes since you approved it

**Comment by phlptp** [comment]
@dnadeau4 just tagging you to have a look if you want and see whats up.

**Pull request merged**
