### PR TITLE
Add github workflow for build

### PR DESCRIPTION
**Pull request by kdheepak**
### Summary

If merged this pull request will add github action support

### CODE REVIEW

**Comment by nightlark** [comment]
Was opening the PR the thing that made actions start running the workflow file? A few weeks ago when I tried setting up a workflow in a fork it didn't seem like it was running the workflow unless I changed the default repository branch to the one with the workflow file in it.

**Comment by kdheepak** [comment]
I just opened the PR and it worked.

**Comment by phlptp** [comment]
Is this PR something we will be merging or was it just a test?

**Comment by kdheepak** [comment]
We can reconsider once github actions goes out of beta.

**Pull request closed without merging**
