### PR TITLE
Ring message benchmark

### PR DESCRIPTION
**Pull request by phlptp**
### Summary

If merged this pull request will add the RingMessageBenchmark

### Proposed changes

- add RingMessageBenchmark
- add a restrictive time policy flag to the forwardingTimeCoordinator

### CODE REVIEW

**Comment by phlptp** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- benchmarks/helics/ringBenchmarks.cpp  8
- benchmarks/helics/echoBenchmarks.cpp  2
- src/helics/application_api/ValueFederate.hpp  10
- benchmarks/helics/ringMessageBenchmarks.cpp  10
         

Clones removed
==============
+ tests/helics/application_api/ValueFederateAdditionalTests.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GMLC-TDC/HELICS/pullRequest?prid=4803295&bid=15983124)

**Comment by phlptp** [comment]
It is my intention to deprecate the register<Interface>Indexed calls in the application_api in HELICS 2.5 and remove them in 3.0.  In favor of the registerIndexed<Interface>  so it is consistent with registerGlobal<Interface>.  

The indexed calls should also be added to the C shared lib for 2.5 release as well.

**Comment by phlptp** [comment]
TODO:
- [ ] Update documentation on `restrictive_time_policy` option
- [ ] make sure there the C++98 API is backwards compatible.  
- [ ] update docs on the benchmark

**Comment by phlptp** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- benchmarks/helics/ringBenchmarks.cpp  8
- src/helics/application_api/ValueFederate.hpp  10
- benchmarks/helics/ringMessageBenchmarks.cpp  10
- benchmarks/helics/echoBenchmarks.cpp  2
         

Clones removed
==============
+ tests/helics/application_api/ValueFederateAdditionalTests.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GMLC-TDC/HELICS/pullRequest?prid=4803295&bid=15983124)

**Comment by phlptp** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- benchmarks/helics/ringMessageBenchmarks.cpp  10
- benchmarks/helics/ringBenchmarks.cpp  8
- src/helics/application_api/ValueFederate.hpp  10
- benchmarks/helics/echoBenchmarks.cpp  2
         

Clones removed
==============
+ tests/helics/application_api/ValueFederateAdditionalTests.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GMLC-TDC/HELICS/pullRequest?prid=4803295&bid=15983124)

**Comment by nightlark** [comment]
> It is my intention to deprecate the registerIndexed calls in the application_api in HELICS 2.5 and remove them in 3.0. In favor of the registerIndexed so it is consistent with registerGlobal.
> 
> The indexed calls should also be added to the C shared lib for 2.5 release as well.

Is it the `register*Indexed` calls that are being deprecated, or the `registerIndexed*` calls?

**Comment by phlptp** [comment]
To be consistent with registerGlobalInterface  I thought all the calls should be similar such that register[Adjective]*[Input|Subscription|Input|Endpoint|Filter],  which means the existing registerPublicationIndexed should be deprecated in favor of registerIndexedPublication and similar for other calls

**Comment by phlptp** [comment]
Part of Issue #892

**Comment by phlptp** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- benchmarks/helics/echoBenchmarks.cpp  2
- benchmarks/helics/ringMessageBenchmarks.cpp  10
- src/helics/application_api/ValueFederate.hpp  10
- benchmarks/helics/ringBenchmarks.cpp  8
         

Clones removed
==============
+ tests/helics/application_api/ValueFederateAdditionalTests.cpp  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GMLC-TDC/HELICS/pullRequest?prid=4803295&bid=15983124)

**Comment by phlptp** [comment]
Just to be clear the reason the indexed thing came up here was I needed an indexed endpoint function and that got me looking at the functions as a whole.    I also note that there are no equivalent functions in the C api yet.  So for 2.5 I am thinking to add those in the C api but not the deprecated versions.

**Pull request merged**
