### PR TITLE
try updating the networking submodule for support for MSYS2 build

### PR DESCRIPTION
**Pull request by phlptp**
### Summary

If merged this pull request will update networking submodule

### CODE REVIEW

**Comment by phlptp** [comment]
@nightlark  how do I trigger an MSYS2 build?

**Comment by nightlark** [comment]
Here are the branch name triggers: https://github.com/GMLC-TDC/HELICS/blob/main/.github/workflows/msys2.yml#L7
```
  push:
    branches:
      - 'msys2/**'
      - 'msys/**'
      - 'msys2-**'
      - 'msys-**'
      - 'mingw64/**'
      - 'mingw/**'
      - 'mingw64-**'
      - 'mingw-**'
```

And a manual run can be triggered from https://github.com/GMLC-TDC/HELICS/actions/workflows/msys2.yml

**Comment by phlptp** [comment]
guess I should have used a `-` in the name instead of `_`

**Comment by phlptp** [comment]
I am not sure what is going on with the MSYS2 CI builds.  I can verify the MSYS2 build works fine with these changes on my system.

**Comment by phlptp** [comment]
@nightlark @kdheepak  need someone to approve these PR's to finalize the release

**Review by kdheepak — APPROVED** [review]

**Pull request merged**
