### PR TITLE
Change C API markdown file

### LINKED ISSUE #1321: Missing C API Function Documentation
* **I'm submitting a ...**
  - [ ] bug
  - [ ] feature request
  - [x] support question

### Feature Request / Support Question

The C API Reference on HELICS readthedocs page is missing the following function documentation

from helics.h:
- helicsErrorInitialize
- helicsErrorClear
- helicsBrokerMakeConnections
- helicsCoreWaitForDisconnect
- helicsCoreMakeConnections
- helicsCoreGetAddress
- helicsCoreConnect
- helicsFederateInfoSetBrokerInitString
- helicsFederateInfoSetBrokerKey
- helicsFederateGlobalError
- helicsFederateLocalError
- helicsFederateEnterInitializingModeCompleted
- helicsFederateRequestTimeAdvance
- helicsFederateAddDependency
- helicsFederateSetLogFile
- helicsFederateLogErrorMessage
- helicsFederateLogWarningMessage
- helicsFederateLogInfoMessage
- helicsFederateLogDebugMessage
- helicsFederateLogLevelMessage
- helicsCoreSetLogFile
- helicsBrokerSetLogFile
- helicsQueryExecuteCompleted

from helicsCallbacks.h
- helicsBrokerSetLoggingCallback
- helicsCoreSetLoggingCallback
- helicsFederateSetLoggingCallback
- helicsFilterSetCustomCallback

from MessageFederate.h
- helicsEndpointIsValid
- helicsEndpointSendMessageObject
- helicsEndpointSendMessageObjectZeroCopy
- helicsEndpointGetMessageObject
- helicsFederateGetMessageObject
- helicsFederateCreateMessageObject
- helicsFederateClearMessages
- helicsEndpointClearMessages
- helicsMessageGetSource
- helicsMessageGetDestination
- helicsMessageGetOriginalDestination
- helicsMessageGetOriginalSource
- helicsMessageGetTime
- helicsMessageGetString
- helicsMessageGetMessageID
- helicsMessageCheckFlag
- helicsMessageGetRawDataSize
- helicsMessageGetRawData
- helicsMessageGetRawDataPointer
- helicsMessageIsValid
- helicsMessageSetSource
- helicsMessageSetDestination
- helicsMessageSetOrginalSource
- helicsMessageSetOriginalDestination
- helicsMessageSetTime
- helicsMessageResize
- helicsMessageReserve
- helicsMessageSetMessageID
- helicsMessageClearFlags
- helicsMessageSetFlagOption
- helicsMessageSetString
- helicsMessageSetData
- helicsMessageAppendData
- helicsMessageCopy

from MessageFilters.h
- helicsFilterIsValid

from ValueFederate.h
- helicsFederateClearUpdates
- helicsFederateRegisterFromPublicationJSON
- helicsFederatePublishJSON
- helicsPublicationIsValid
- helicsInputIsValid
- helicsInputGetInjectionUnits
- helicsInputGetExtractionUnits
- helicsPublicationSetMinimumChange
- helicsInputSetMiniumChange
- helicsInputClearUpdate

### PR DESCRIPTION
**Pull request by kdheepak**
When merged this will fix the C API documentation.

This script was used to generate the C API markdown file:

https://gist.github.com/kdheepak/84f8da048140c3f632633fabfdec1f97

Resolves #1321

### CODE REVIEW

**Comment by phlptp** [comment]
Can we put this script in the repo and run it as part of the github action for generating interface files or something else so it gets updated automatically?

**Comment by kdheepak** [comment]
We can but this script requires the HELICS python library built and
accessible in the current path. I have to look into how that would work on
readthedocs.

**Comment by kdheepak** [comment]
We can have a github action do this automatically.

**Comment by nightlark** [comment]
Can the dependency on the HELICS python interface be removed by pulling the exported symbol names from the shared library directly? `nm -C` to give the script a list of unmangled symbol names?

**Comment by nightlark** [comment]
Though that still requires compiling HELICS to get the information. It would be nice to skip compiling.

**Comment by kdheepak** [comment]
Maybe this PR shouldn't be blocked by this? It seems like a short term solution but I don't want to require building helics on readthedocs. Maybe we can revisit this request once we move away from readthedocs, if we ever do so.

**Comment by nightlark** [comment]
I think automated updates to doc source files would be a separate change.

**Comment by phlptp** [comment]
I was thinking some thing similar to the interface file updates.  Rather than as part of the rtd build itself.


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On May 16, 2020 at 11:15:47 AM PDT, Ryan Mast <notifications@github.com> wrote:

I think automated updates to doc source files would be a separate change.

**Comment by kdheepak** [comment]
Ah, got it. I can update the script to use `nm` instead.

**Comment by kdheepak** [comment]
I don't know if we can use `nm` to capture this correctly btw. `nm` will work for all the symbols in that are functions but `enum` are not stored as symbols. 

Ideally, we'd use a C header processor / LLVM and read the header files and print out this file accordingly.

**Pull request merged**
