### PR TITLE
V3b cmd line cleanup

### PR DESCRIPTION
**Pull request by trevorhardy**
### Summary

If merged this pull request will standardize the names of the federate options to conform to the v3 standard.

### CODE REVIEW

**Review by phlptp — APPROVED** [review]

**Comment by phlptp** [comment]
Would it be worth adding a discussion on the options/command line naming to the [style guide](https://github.com/GMLC-TDC/HELICS/blob/helics3/docs/developer-guide/style.md)  Then we have a reference when we inevitably add more?

**Comment by trevorhardy** [comment]
That's a good idea. Let me try to add something and see if I can express it succinctly.

**Comment by trevorhardy** [comment]
@phlptp, I've added an additional rule to the developer style guide in this branch; let me know what you think.

**Comment by phlptp** [comment]
looks good!  You can merge the formatting change or fix it yourself.  Then once the builds finish assuming no CI errors come up, we can merge it.

**Pull request merged**
