### PR TITLE
Change default console logger

### PR DESCRIPTION
**Pull request by phlptp**
### Summary

If merged this pull request will Update the console loggers to use a specific one instead of the default.  Then flush according to the policy.

### CODE REVIEW

**Comment by phlptp** [comment]
@kdheepak  have you had a chance to look  at this yet?

**Comment by phlptp** [comment]
@kdheepak   Can you look at this today?  I want get everything merged and get a release out by tomorrow?

**Comment by kdheepak** [comment]
This works great! `--dumplog` has regressed to not working, but the logging now works while the federate is running in Python.

**Comment by kdheepak** [comment]
This is the initialization strings that I'm using for the federate and the broker.

```
brokerinitstring = "-f 2 --name=mainbroker --log_level=7 --dumplog"
federateinitstring = "--broker=mainbroker --log_level=7 --federates=1 --dumplog"
```

**Comment by kdheepak** [comment]
I just did a pull. This is great! This provides super detailed and verbose logs when needed.

**Comment by kdheepak** [comment]
```
$ python tests/pisender.py
PI SENDER: Helics version = 2.5.2-logging_update-gfdc29c4b-dirty (2020-08-19)
Creating Broker
[2020-08-19 15:09:44.443] [console] [info] mainbroker (0)::connecting
[2020-08-19 15:09:44.444] [console] [info] mainbroker (0)::||connected on tcp://127.0.0.1:23404
Created Broker
[2020-08-19 15:09:44.444] [console] [trace] mainbroker (0)::|| priority_cmd:unknown -1 from 0
Checking if Broker is connected
Checked if Broker is connected
Broker created and connected
[2020-08-19 15:09:44.448] [console] [trace] mainbroker (1)::|| priority_cmd:reg_broker:TestA Federate from -2010000000
[2020-08-19 15:09:44.448] [console] [info] mainbroker (1)::registering broker TestA Federate(1879048192) on route 1
[2020-08-19 15:09:44.449] [console] [trace] TestA Federate (0)::|| priority_cmd:broker_ack:From 1 from 1
[2020-08-19 15:09:44.550] [console] [trace] TestA Federate (1879048192)::|| priority_cmd:reg_fed:TestA Federate from 0
[2020-08-19 15:09:44.550] [console] [trace] mainbroker (1)::|| priority_cmd:reg_fed:TestA Federate from 1879048192
[2020-08-19 15:09:44.550] [console] [info] mainbroker (1)::registering federate TestA Federate(131072) on route 1
[2020-08-19 15:09:44.551] [console] [trace] TestA Federate (1879048192)::|| priority_cmd:fed_ack:TestA Federate--131072 from 1
PI SENDER: Value federate created
[2020-08-19 15:09:44.551] [console] [info] TestA Federate (0)::registering PUB testA
PI SENDER: Publication registered
[2020-08-19 15:09:44.551] [console] [trace] TestA Federate (1879048192)::|| cmd:reg_pub:From 131072 from 131072
[2020-08-19 15:09:44.551] [console] [trace] TestA Federate (1879048192)::|| cmd:init:From 131072 from 131072
[2020-08-19 15:09:44.552] [console] [trace] mainbroker (1)::|| cmd:reg_pub:From 131072 from 131072 to 0
[2020-08-19 15:09:44.552] [console] [trace] mainbroker (1)::|| cmd:init:From 1879048192 from 1879048192 to 0
[2020-08-19 15:09:47.844] [console] [trace] mainbroker (1)::|| priority_cmd:reg_broker:TestB Federate from -2010000000
[2020-08-19 15:09:47.844] [console] [info] mainbroker (1)::registering broker TestB Federate(1879048193) on route 2
[2020-08-19 15:09:47.948] [console] [trace] mainbroker (1)::|| priority_cmd:reg_fed:TestB Federate from 1879048193
[2020-08-19 15:09:47.948] [console] [info] mainbroker (1)::registering federate TestB Federate(131073) on route 2
[2020-08-19 15:09:47.950] [console] [trace] mainbroker (1)::|| cmd:add_named_publication:From 131073 from 131073 to 0
[2020-08-19 15:09:47.950] [console] [trace] mainbroker (1)::|| cmd:init:From 1879048193 from 1879048193 to 0
[2020-08-19 15:09:47.950] [console] [debug] root (1)::entering initialization mode
[2020-08-19 15:09:47.950] [console] [info] root (1)::Federation Summary>
	2 federates [min 2]
	0/2 brokers/cores [min 0]
	1 publications
	0 inputs
	0 endpoints
	0 filters
<<<<<<<<<
[2020-08-19 15:09:47.950] [console] [trace] TestA Federate (1879048192)::|| cmd:add_subscriber:From 131073 from 131073
[2020-08-19 15:09:47.950] [console] [trace] TestA Federate (1879048192)::|| cmd:init_grant:From 1 from 1
[2020-08-19 15:09:47.950] [console] [trace] TestA Federate (1879048192)::|| cmd:exec_request:From 131072 from 131072
[2020-08-19 15:09:47.950] [console] [trace] TestA Federate (1879048192)::|| cmd:exec_grant:From 131072 from 131072
PI SENDER: Entering execution mode
[2020-08-19 15:09:47.951] [console] [trace] mainbroker (1)::|| cmd:exec_request:From 131072 from 131072 to 131073
[2020-08-19 15:09:47.951] [console] [trace] TestA Federate (1879048192)::|| cmd:time_request:From (131072) Time(0.01, 5.0, 9223372036.854776) to (131073) from 131072
[2020-08-19 15:09:47.951] [console] [trace] TestA Federate (1879048192)::|| cmd:time_grant:From (131072) Granted Time(5.0) to (131073) from 131072
[2020-08-19 15:09:47.951] [console] [trace] mainbroker (1)::|| cmd:exec_grant:From 131072 from 131072 to 131073
[2020-08-19 15:09:47.951] [console] [trace] TestA Federate (1879048192)::|| cmd:pub:From (131072) handle(0) size 9 at 5.0 to 131073 from 131072
PI SENDER: Sending value pi = 3.141592653589793 at time 5.0 to PI RECEIVER
[2020-08-19 15:09:47.951] [console] [trace] mainbroker (1)::|| cmd:time_request:From (131072) Time(0.01, 5.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:47.951] [console] [trace] mainbroker (1)::|| cmd:time_grant:From (131072) Granted Time(5.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:47.951] [console] [trace] mainbroker (1)::|| cmd:pub:From (131072) handle(0) size 9 at 5.0 to 131073 from 131072 to 131073
PI SENDER: Sending value pi = 3.141592653589793 at time 6.0 to PI RECEIVER
[2020-08-19 15:09:48.954] [console] [trace] TestA Federate (1879048192)::|| cmd:time_request:From (131072) Time(5.01, 6.0, 9223372036.854776) to (131073) from 131072
[2020-08-19 15:09:48.954] [console] [trace] TestA Federate (1879048192)::|| cmd:time_grant:From (131072) Granted Time(6.0) to (131073) from 131072
[2020-08-19 15:09:48.954] [console] [trace] TestA Federate (1879048192)::|| cmd:pub:From (131072) handle(0) size 9 at 6.0 to 131073 from 131072
[2020-08-19 15:09:48.955] [console] [trace] mainbroker (1)::|| cmd:time_request:From (131072) Time(5.01, 6.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:48.955] [console] [trace] mainbroker (1)::|| cmd:time_grant:From (131072) Granted Time(6.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:48.955] [console] [trace] mainbroker (1)::|| cmd:pub:From (131072) handle(0) size 9 at 6.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:49.956] [console] [trace] TestA Federate (1879048192)::|| cmd:time_request:From (131072) Time(6.01, 7.0, 9223372036.854776) to (131073) from 131072
[2020-08-19 15:09:49.956] [console] [trace] TestA Federate (1879048192)::|| cmd:time_grant:From (131072) Granted Time(7.0) to (131073) from 131072
PI SENDER: Sending value pi = 3.141592653589793 at time 7.0 to PI RECEIVER
[2020-08-19 15:09:49.956] [console] [trace] TestA Federate (1879048192)::|| cmd:pub:From (131072) handle(0) size 9 at 7.0 to 131073 from 131072
[2020-08-19 15:09:49.956] [console] [trace] mainbroker (1)::|| cmd:time_request:From (131072) Time(6.01, 7.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:49.956] [console] [trace] mainbroker (1)::|| cmd:time_grant:From (131072) Granted Time(7.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:49.957] [console] [trace] mainbroker (1)::|| cmd:pub:From (131072) handle(0) size 9 at 7.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:50.959] [console] [trace] TestA Federate (1879048192)::|| cmd:time_request:From (131072) Time(7.01, 8.0, 9223372036.854776) to (131073) from 131072
PI SENDER: Sending value pi = 3.141592653589793 at time 8.0 to PI RECEIVER
[2020-08-19 15:09:50.960] [console] [trace] TestA Federate (1879048192)::|| cmd:time_grant:From (131072) Granted Time(8.0) to (131073) from 131072
[2020-08-19 15:09:50.960] [console] [trace] TestA Federate (1879048192)::|| cmd:pub:From (131072) handle(0) size 9 at 8.0 to 131073 from 131072
[2020-08-19 15:09:50.960] [console] [trace] mainbroker (1)::|| cmd:time_request:From (131072) Time(7.01, 8.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:50.960] [console] [trace] mainbroker (1)::|| cmd:time_grant:From (131072) Granted Time(8.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:50.960] [console] [trace] mainbroker (1)::|| cmd:pub:From (131072) handle(0) size 9 at 8.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:51.963] [console] [trace] TestA Federate (1879048192)::|| cmd:time_request:From (131072) Time(8.01, 9.0, 9223372036.854776) to (131073) from 131072
PI SENDER: Sending value pi = 3.141592653589793 at time 9.0 to PI RECEIVER
[2020-08-19 15:09:51.963] [console] [trace] TestA Federate (1879048192)::|| cmd:time_grant:From (131072) Granted Time(9.0) to (131073) from 131072
[2020-08-19 15:09:51.963] [console] [trace] TestA Federate (1879048192)::|| cmd:pub:From (131072) handle(0) size 9 at 9.0 to 131073 from 131072
[2020-08-19 15:09:51.964] [console] [trace] mainbroker (1)::|| cmd:time_request:From (131072) Time(8.01, 9.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:51.964] [console] [trace] mainbroker (1)::|| cmd:time_grant:From (131072) Granted Time(9.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:51.964] [console] [trace] mainbroker (1)::|| cmd:pub:From (131072) handle(0) size 9 at 9.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:52.966] [console] [trace] TestA Federate (1879048192)::|| cmd:disconnect:From 131072 from 131072
[2020-08-19 15:09:52.967] [console] [trace] TestA Federate (1879048192)::|| cmd:disconnect:From 131072 from 131072
[2020-08-19 15:09:52.967] [console] [trace] TestA Federate (1879048192)::|| cmd:disconnect:From 131072 from 131072
[2020-08-19 15:09:52.967] [console] [trace] mainbroker (1)::|| cmd:disconnect:From 131072 from 131072 to 131073
[2020-08-19 15:09:52.967] [console] [trace] mainbroker (1)::|| cmd:disconnect:From 1879048192 from 1879048192 to 0
[2020-08-19 15:09:52.967] [console] [info] mainbroker (0)::got disconnect from TestA Federate(1879048192)
[2020-08-19 15:09:52.967] [console] [trace] TestA Federate (1879048192)::|| cmd:disconnect core acknowledge:From 1 from 1
PI SENDER: Federate finalized
[2020-08-19 15:09:52.968] [console] [trace] mainbroker (1)::|| cmd:disconnect:From 1879048193 from 1879048193 to 0
[2020-08-19 15:09:52.968] [console] [info] mainbroker (0)::got disconnect from TestB Federate(1879048193)
[2020-08-19 15:09:53.010] [console] [trace] TestA Federate (1879048192)::|| cmd:stop:From 0 from 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:broker_ack:From 1 from 1 to 1879048192
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:reg_fed:TestA Federate from 0 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:fed_ack:TestA Federate--131072 from 1 to 131072
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:reg_pub:From 131072 from 131072 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:init:From 131072 from 131072 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:add_subscriber:From 131073 from 131073 to 131072
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:init_grant:From 1 from 1 to 1879048192
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:exec_request:From 131072 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:exec_grant:From 131072 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(0.01, 5.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(5.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] mainbroker (1)::|| cmd:stop:From 0 from 0 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:unknown -1 from 0 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:reg_broker:TestA Federate from -2010000000 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:reg_fed:TestA Federate from 1879048192 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:reg_pub:From 131072 from 131072 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:init:From 1879048192 from 1879048192 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:reg_broker:TestB Federate from -2010000000 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:reg_fed:TestB Federate from 1879048193 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:add_named_publication:From 131073 from 131073 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:init:From 1879048193 from 1879048193 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:exec_request:From 131072 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:exec_grant:From 131072 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 5.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(5.01, 6.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(6.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(0.01, 5.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 6.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:tick:From 0 from 0 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(6.01, 7.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(5.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(7.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 7.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 5.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(7.01, 8.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(8.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 8.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(8.01, 9.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(9.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 9.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:disconnect:From 131072 from 131072 to 131072
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:disconnect:From 131072 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:disconnect:From 131072 from 131072 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(5.01, 6.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.039] [console] [trace] || dl cmd:disconnect core acknowledge:From 1 from 1 to 1879048192
[2020-08-19 15:09:53.039] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(6.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.039] [console] [trace] || dl cmd:stop:From 0 from 0 to 0
[2020-08-19 15:09:53.039] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 6.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.039] [console] [trace] || dl cmd:tick:From 0 from 0 to 0
[2020-08-19 15:09:53.039] [console] [trace] || dl cmd:time_request:From (131072) Time(6.01, 7.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.039] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(7.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.039] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 7.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.039] [console] [trace] || dl cmd:time_request:From (131072) Time(7.01, 8.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.039] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(8.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.040] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 8.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.040] [console] [trace] || dl cmd:time_request:From (131072) Time(8.01, 9.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.040] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(9.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.040] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 9.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.040] [console] [trace] || dl cmd:disconnect:From 131072 from 131072 to 131073
[2020-08-19 15:09:53.040] [console] [trace] || dl cmd:disconnect:From 1879048192 from 1879048192 to 0
[2020-08-19 15:09:53.040] [console] [trace] || dl cmd:disconnect:From 1879048193 from 1879048193 to 0
[2020-08-19 15:09:53.040] [console] [trace] || dl cmd:stop:From 0 from 0 to 0
[2020-08-19 15:09:53.040] [console] [info] mainbroker (0)::||disconnecting
PI SENDER: Broker disconnected
```


```
$ python tests/pireceiver.py
PI RECEIVER: Helics version = 2.5.2-logging_update-gfdc29c4b-dirty (2020-08-19)
PI RECEIVER: Creating Federate Info
PI RECEIVER: Setting Federate Info Name
PI RECEIVER: Setting Federate Info Core Type
PI RECEIVER: Setting Federate Info Init String
PI RECEIVER: Setting Federate Info Time Delta
PI RECEIVER: Creating Value Federate
[2020-08-19 15:09:47.844] [console] [trace] TestB Federate (0)::|| priority_cmd:broker_ack:From 1 from 1
[2020-08-19 15:09:47.948] [console] [trace] TestB Federate (1879048193)::|| priority_cmd:reg_fed:TestB Federate from 0
[2020-08-19 15:09:47.949] [console] [trace] TestB Federate (1879048193)::|| priority_cmd:fed_ack:TestB Federate--131073 from 1
PI RECEIVER: Value federate created
[2020-08-19 15:09:47.949] [console] [info] TestB Federate (0)::registering Input
[2020-08-19 15:09:47.949] [console] [trace] TestB Federate (1879048193)::|| cmd:reg_input:From 131073 from 131073
PI RECEIVER: Subscription registered
[2020-08-19 15:09:47.949] [console] [trace] TestB Federate (1879048193)::|| cmd:add_named_publication:From 131073 from 131073
[2020-08-19 15:09:47.950] [console] [trace] TestB Federate (1879048193)::|| cmd:init:From 131073 from 131073
[2020-08-19 15:09:47.950] [console] [trace] TestB Federate (1879048193)::|| cmd:add publisher:From 131072 from 131072
[2020-08-19 15:09:47.950] [console] [trace] TestB Federate (1879048193)::|| cmd:init_grant:From 1 from 1
[2020-08-19 15:09:47.951] [console] [trace] TestB Federate (1879048193)::|| cmd:exec_request:From 131072 from 131072
PI RECEIVER: Entering execution mode
[2020-08-19 15:09:47.951] [console] [trace] TestB Federate (1879048193)::|| cmd:exec_grant:From 131072 from 131072
[2020-08-19 15:09:47.951] [console] [trace] TestB Federate (1879048193)::|| cmd:time_request:From (131072) Time(0.01, 5.0, 9223372036.854776) to (131073) from 131072
[2020-08-19 15:09:47.951] [console] [trace] TestB Federate (1879048193)::|| cmd:time_grant:From (131072) Granted Time(5.0) to (131073) from 131072
[2020-08-19 15:09:47.951] [console] [trace] TestB Federate (1879048193)::|| cmd:pub:From (131072) handle(0) size 9 at 5.0 to 131073 from 131072
[2020-08-19 15:09:48.955] [console] [trace] TestB Federate (1879048193)::|| cmd:time_request:From (131072) Time(5.01, 6.0, 9223372036.854776) to (131073) from 131072
[2020-08-19 15:09:48.955] [console] [trace] TestB Federate (1879048193)::|| cmd:time_grant:From (131072) Granted Time(6.0) to (131073) from 131072
[2020-08-19 15:09:48.955] [console] [trace] TestB Federate (1879048193)::|| cmd:pub:From (131072) handle(0) size 9 at 6.0 to 131073 from 131072
PI RECEIVER: Received value = 3.141593 at time 5.0 from PI SENDER
[2020-08-19 15:09:49.957] [console] [trace] TestB Federate (1879048193)::|| cmd:time_request:From (131072) Time(6.01, 7.0, 9223372036.854776) to (131073) from 131072
[2020-08-19 15:09:49.957] [console] [trace] TestB Federate (1879048193)::|| cmd:time_grant:From (131072) Granted Time(7.0) to (131073) from 131072
PI RECEIVER: Received value = 3.141593 at time 6.0 from PI SENDER
[2020-08-19 15:09:49.957] [console] [trace] TestB Federate (1879048193)::|| cmd:pub:From (131072) handle(0) size 9 at 7.0 to 131073 from 131072
[2020-08-19 15:09:50.961] [console] [trace] TestB Federate (1879048193)::|| cmd:time_request:From (131072) Time(7.01, 8.0, 9223372036.854776) to (131073) from 131072
[2020-08-19 15:09:50.961] [console] [trace] TestB Federate (1879048193)::|| cmd:time_grant:From (131072) Granted Time(8.0) to (131073) from 131072
[2020-08-19 15:09:50.961] [console] [trace] TestB Federate (1879048193)::|| cmd:pub:From (131072) handle(0) size 9 at 8.0 to 131073 from 131072
PI RECEIVER: Received value = 3.141593 at time 7.0 from PI SENDER
[2020-08-19 15:09:51.964] [console] [trace] TestB Federate (1879048193)::|| cmd:time_request:From (131072) Time(8.01, 9.0, 9223372036.854776) to (131073) from 131072
[2020-08-19 15:09:51.964] [console] [trace] TestB Federate (1879048193)::|| cmd:time_grant:From (131072) Granted Time(9.0) to (131073) from 131072
PI RECEIVER: Received value = 3.141593 at time 8.0 from PI SENDER
[2020-08-19 15:09:51.964] [console] [trace] TestB Federate (1879048193)::|| cmd:pub:From (131072) handle(0) size 9 at 9.0 to 131073 from 131072
[2020-08-19 15:09:52.967] [console] [trace] TestB Federate (1879048193)::|| cmd:disconnect:From 131072 from 131072
PI RECEIVER: Received value = 3.141593 at time 9.0 from PI SENDER
PI RECEIVER: Received value = 3.141593 at time 100.0 from PI SENDER
PI RECEIVER: Received value = 3.141593 at time 100.01 from PI SENDER
[2020-08-19 15:09:52.968] [console] [trace] TestB Federate (1879048193)::|| cmd:disconnect:From 131073 from 131073
[2020-08-19 15:09:52.968] [console] [trace] TestB Federate (1879048193)::|| cmd:disconnect:From 131073 from 131073
[2020-08-19 15:09:52.969] [console] [trace] TestB Federate (1879048193)::|| cmd:disconnect core acknowledge:From 1 from 1
[2020-08-19 15:09:53.010] [console] [trace] TestB Federate (1879048193)::|| cmd:stop:From 0 from 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:broker_ack:From 1 from 1 to 1879048193
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:reg_fed:TestB Federate from 0 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:fed_ack:TestB Federate--131073 from 1 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:reg_input:From 131073 from 131073 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:add_named_publication:From 131073 from 131073 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:init:From 131073 from 131073 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:add publisher:From 131072 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:init_grant:From 1 from 1 to 1879048193
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:exec_request:From 131072 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:exec_grant:From 131072 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(0.01, 5.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(5.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 5.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(5.01, 6.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(6.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 6.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(6.01, 7.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(7.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 7.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(7.01, 8.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(8.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 8.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_request:From (131072) Time(8.01, 9.0, 9223372036.854776) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:time_grant:From (131072) Granted Time(9.0) to (131073) from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:pub:From (131072) handle(0) size 9 at 9.0 to 131073 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:tick:From 0 from 0 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:disconnect:From 131072 from 131072 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:disconnect:From 131073 from 131073 to 131073
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:disconnect:From 131073 from 131073 to 0
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:disconnect core acknowledge:From 1 from 1 to 1879048193
[2020-08-19 15:09:53.010] [console] [trace] || dl cmd:stop:From 0 from 0 to 0
PI RECEIVER: Federate finalized
```

**Pull request merged**
