### PR TITLE
HELICS 3 PR generation full git clone

### PR DESCRIPTION
**Pull request by nightlark**
### Summary

If merged this pull request will get a full clone of the git repository for workflows that generate PRs.

### Proposed changes

- fetch all git history for swig update workflow
- fetch all git history for formatting workflow

### CODE REVIEW

**Comment by phlptp** [comment]
Do we want to merge this first or the converters.  
And I presume this will effect the develop/master branches as well so will need to be updated there as well?

**Comment by nightlark** [comment]
I'll cherry-pick the merge commit for the develop/master branch.

**Comment by nightlark** [comment]
Merge order doesn't matter.

**Comment by phlptp** [comment]
sounds good

**Pull request merged**
