### PR TITLE
Add blacken-docs pre-commit hook

### PR DESCRIPTION
**Pull request by nightlark**
### Summary

If merged this pull request will cherry-pick the addition of the blacken-docs pre-commit hook from #2152

### Proposed changes

- Add blacken-docs pre-commit hook

### CODE REVIEW

**Comment by phlptp** [comment]
good call pulling this out.  Saw the pre-commit check in another project and thought that it looked useful

**Comment by nightlark** [comment]
Nice how it fixes up the extra indentation we had.

**Review by phlptp — APPROVED** [review]

**Comment by phlptp** [comment]
looks like there are a few parse issues in the docs that need to be addressed yet

**Comment by nightlark** [comment]
It seems to not like the start of a code block (while, if, etc) without any subsequent lines. I've added `pass` commands in those cases with a "placeholder" comment.

**Pull request merged**
