### PR TITLE
add codespell check

### PR DESCRIPTION
**Pull request by phlptp**
### Summary

If merged this pull request will add a codespell check

### CODE REVIEW

**Comment by phlptp** [comment]
@nightlark 
any idea what this is from 
```
Switched to a new branch 'pre-commit/update-codespell'
[pre-commit/update-codespell 51f70c4] Automated formatting of doc/script files
 59 files changed, 111 insertions(+), 111 deletions(-)
To https://github.com/GMLC-TDC/HELICS
 + a9c2737...51f70c4 pre-commit/update-codespell -> pre-commit/update-codespell (forced update)
Branch 'pre-commit/update-codespell' set up to track remote branch 'pre-commit/update-codespell' from 'origin'.
curl: (22) The requested URL returned error: 422 Unprocessable Entity
```

It seems to update the PR correctly so I am not sure what is going on here in the action

**Comment by nightlark** [comment]
Something the GitHub API is returning.

**Comment by nightlark** [comment]
Maybe it's the response when a PR already exists.

**Comment by phlptp** [comment]
Does the clang format PR do the same thing?

**Comment by nightlark** [comment]
Probably. I think the output message could be suppressed, there isn’t an API for checking if a PR exists by branch/name other than going through the list of PRs (uses pagination).

**Comment by phlptp** [comment]
It doesn't look like it had the same error on the first one, so must be something to do with the PR already existing.

**Pull request merged**
