### PR TITLE
Iteration example

### PR DESCRIPTION
**Pull request by eranschweitzer**
### Summary

If merged this pull request will document the iteration example added to the examples repository as well as elaborate more generally on how iteration is intended to work under the advanced topics section of the documentation

### Proposed changes

* Only change the documentation
* Adds clearer information, located in one place on how iteration (both initialization and during time) are intended to be implemented using HELICS.

### CODE REVIEW

**Comment by phlptp** [comment]
looks like a few markdown warnings that need to be resolved.  Hopefully pretty quick

**Comment by eranschweitzer** [comment]
@phlptp  I'm happy to fix markdown issues, I'm just not sure how to find them. 
Where exactly are you seeing the markdown issues? I see that the readthedocs check successfully built the docs.

**Comment by phlptp** [comment]
They usually are not errors so most of the time the readthedocs works fine, just the precommit check which mainly deals with formatting and consistency.  

https://results.pre-commit.ci/run/github/93080515/1653339870.SVP3TE8_R-mqntMG3Txnvg

It fixes them most of the time but can't really do that for some of the markdown stuff.

**Comment by phlptp** [comment]
@trevorhardy  can you take a look at this to double check.  It looks fine to me but I didn't go through it in detail yet.

**Comment by trevorhardy** [comment]
Yup; on my to-do list. @phlptp, are you hoping to get this into the 3.2.1 release? If so I can prioritize this.

**Comment by phlptp** [comment]
Yes,  Hopefully this week assuming we can get the matlab interface working

**Review by trevorhardy — APPROVED** [review]

**Comment by phlptp** [comment]
looks like a couple spelling issues then we can merge this
https://results.pre-commit.ci/run/github/93080515/1653593847.wfuEs0l5SkqdKUgBe6-yHA

**Comment by trevorhardy** [comment]
Corrections made; I didn't know our CI did spelling!

**Pull request merged**
