### PR TITLE
Use latest gcc and clang releases for CI builds

### PR DESCRIPTION
**Pull request by nightlark**
### Summary

If merged this pull request will bump the CI builds for the newest gcc and clang builds from gcc 10 to gcc 11, and clang 10 to clang 12. Addresses #1962 and #1963 

### Proposed changes

- Update the gcc-10 builder to gcc-11
- Update the clang-10 builder to clang-12

### CODE REVIEW

**Comment by nightlark** [comment]
@phlptp I'm having trouble finding an mpi package on Fedora that includes working `mpicc` commands; is gcc 11 not available on Ubuntu yet?

**Comment by phlptp** [comment]
No they came out around the same time, so gcc 11 won't be on ubuntu to 21.10 release

**Comment by nightlark** [comment]
I figured out how to get `mpicc` working on Fedora; not sure if there's an easy way to make sure `module load mpi` runs in the Dockerfile or if the CI yaml file will need to be changed to run the command.

**Comment by nightlark** [comment]
Both clang12 and gcc11 builds are working as well as the previous compilers - just intermittent failing tests now.

**Review by phlptp — APPROVED** [review]

**Pull request merged**
