### PR TITLE
Windows build instructions

### PR DESCRIPTION
**Pull request by eranschweitzer**
### Summary

If merged this pull request will improve the documentation for how to build custom branches of HELICS on windows using Visual Studio and linking the custom `helics.dll` to pyhelics.

### Proposed changes

Documentation changes only.

### CODE REVIEW

**Comment by nightlark** [comment]
The PR target branch should be changed to `develop` instead of `main` (I can't seem to do this from the GH mobile iOS app).

There are a few places with system paths listed that include a user name (powershell "prompt"; could probably just remove the current directory path and make it `>` or try to make the path something generic).

**Review by trevorhardy — APPROVED** [review]
I did a little clean-up (mostly formatting).

**Comment by eranschweitzer** [comment]
Thanks @trevorhardy! Based on your corrections and comments from @nightlark it seems like there is nothing more for me to do 😃 (though any other change requests are welcomed).

**Review by nightlark — COMMENTED** [review]
I think removing the leading space before all of the lines that fall within a numbered bullet point has messed up some of the formatting? The RTD/GitHub markdown parsers no longer consider any of the lines after the first one to be part of the contents of the numbered list entry they fall under.

When that formatting is correct, I don't think bolding the numbers is necessary since the start and end of the content for each step stands out based on the indentation. The bolded numbered list style also differs from every other numbered list in the docs -- if that's something we want to do, I think bolding numbers would be better handled by changing the CSS used by the RTD theme.

**Comment by eranschweitzer** [comment]
@nightlark, the number formatting was not working correctly already, because the numbering is reset every time an item is longer and or includes something like code block.

If you look at the *current* documentation: https://docs.helics.org/en/latest/user-guide/installation/windows.html
you'll see that there are numbers 1-5, then it resets and we have 1-2, then 1-2 again, then two 1s in a row and another 2.

I've run into this problem many times and at some point just gave up on trying to fix it.
My solution is to *go around* the automatic numbering and create the numbered list manually.
I'm not married to the formatting, we can remove the bold etc. However, what I don't know is how to get the indent the way the automatic numbered lists gets it.

I'm open to any and all suggestions but I don't know how to get the number list to behave in markdown the way that you would like it to.

**Review by phlptp — APPROVED** [review]

**Comment by nightlark** [comment]
Oh this is one of the pages that already had broken formatting; let's skip fixing it and it can be fixed in some future pass that includes the other doc pages with formatting issues.

The numbers resetting are almost always from missing indentation after a line split or the code block (\`\`\`) directives not being indented.

* Not indented
```bash
    git clone ...
```
* Indented
  ```bash
  git clone ...
  ```
---
    * Not indented
    ```bash
      git clone ...
    ```
    * Indented
      ```bash
      git clone ...
      ```

**Review by nightlark — APPROVED** [review]

**Pull request merged**
