### PR TITLE
Make boost optional

### PR DESCRIPTION
**Pull request by phlptp**
### Summary

If merged this pull request will remove boost from the core and application api completely apart from the IPC_core.  

### Proposed changes

- use demangle from utilities library
- update the utilities library
- use randomString generation from the utilities library
- add DISABLE_BOOST flag to force removal of boost even if it otherwise could be found

### CODE REVIEW

**Comment by phlptp** [comment]
@nightlark  can you update one of the travis tests to use the DISABLE_BOOST option for testing.  I wasn't entirely sure I knew what to tweak and you might be able to do it faster.

**Comment by nightlark** [comment]
That should enable the option on the clang 3.6 build. Boost might still get downloaded+cache, getting rid of that step will require some more changes that will happen when trying out docker images for Travis builds.

**Comment by nightlark** [comment]
Should this PR be merged to develop?

**Comment by phlptp** [comment]
Go ahead and merge if you are good with it.

Philip


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On September 3, 2019 at 6:06:57 PM PDT, Ryan Mast <notifications@github.com> wrote:

Should this PR be merged to develop?

**Comment by nightlark** [comment]
Should the base get changed from master to develop first?

**Pull request merged**
